FetchApplication:
   Kernel_FetchApplication_with_langcode_smoke:
      endPoint: /v1/masterdata/applicationtypes/{langcode}
      role: admin
      restMethod: get
      inputTemplate: kernel/FetchApplication/fetchApplication
      outputTemplate: kernel/FetchApplication/fetchApplicationResult
      input: '{
  "code": "$REMOVE$",
  "langcode": "eng"
}'
      output: '{
"applicationtypes": [{
			"langCode": "eng",
			"code": "$IGNORE$",
			"isActive": true
		}]
}'